# This config file is required for Black.
# Unforunately, black does not support setup.cfg (refer to link).
# https://github.com/psf/black/issues/683#issuecomment-490236406

[tool.black]
# Docs: https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html
line-length = 88
target-version = ['py39']
include = '\.pyi?$'
exclude = '''
/(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.idea
    | venv
    | _build
    | buck-out
    | build
    | dist
    | docs
    | config
    | conda
    | analysis_data_preprocess
 )/
'''

[tool.isort]
# Docs: https://pycqa.github.io/isort/docs/configuration/options.html#example-pyprojecttoml_4
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88
skip = "e3sm_diags/e3sm_diags_driver.py"

[tool.pytest.ini_options]
# Docs: https://docs.pytest.org/en/7.2.x/reference/customize.html#configuration
junit_family = "xunit2"
addopts = "--cov=e3sm_diags --cov-report term --cov-report html:tests_coverage_reports/htmlcov --cov-report xml:tests_coverage_reports/coverage.xml -s --ignore=tests/integration"
python_files = ["tests.py", "test_*.py"]
testpaths = "tests/e3sm_diags"
filterwarnings = "ignore:.*yaksa"

[tool.mypy]
# Docs: https://mypy.readthedocs.io/en/stable/config_file.html
python_version = 3.10
check_untyped_defs = true
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
exclude = ["analysis_data_preprocess", "model_data_preprocess"]
