# Conda development environment for testing local source code changes to `e3sm_diags` before merging them to production (`master` branch).
name: e3sm_diags_dev
channels:
  - conda-forge
  - defaults
dependencies:
  # Base
  # =======================
  - python >=3.9
  - pip
  - setuptools
  - beautifulsoup4
  - cartopy >=0.17.0
  - cartopy_offlinedata
  - cf-units
  - dask <2024.12.0
  - esmpy >=8.4.0
  - lxml
  - mache >=0.15.0
  - matplotlib-base >=3.8.2
  - netcdf4
  - output_viewer >=1.3.0
  - numpy >=2.0.0,<3.0.0
  - scipy
  - shapely >=2.0.0,<3.0.0
  - xarray >=2024.3.0
  - xcdat >=0.7.3,<1.0.0
  - xesmf >=0.8.7
  - xskillscore >=0.0.20
  # Testing
  # =======================
  - pytest
  - pytest-cov
  # Documentation
  # =======================
  - sphinx
  - sphinx_rtd_theme
  - sphinx-multiversion
  # Quality Assurance Tools
  # =======================
  # Run `pre-commit autoupdate` to get the latest pinned versions of 'rev' in
  # `.pre-commit.config.yaml`, then update the pinned versions here.
  - black=23.9.1
  - flake8=6.1.0
  - flake8-isort=6.1.0
  - isort=5.12.0
  - mypy=1.5.1
  - pre-commit >=3.0.0
  - types-PyYAML >=6.0.0
  # Developer Tools
  # =======================
  - tbump=6.9.0
  - ipykernel
