# Conda development environment for testing local source code changes to `e3sm_diags` before merging them to production (`master` branch).
name: e3sm_diags_dev
channels:
  - conda-forge
dependencies:
  # Base
  # =======================
  - python >=3.11,<3.14
  - pip
  - setuptools
  - beautifulsoup4
  - cartopy >=0.17.0
  - cartopy_offlinedata
  - cf-units
  - dask !=2024.12.0,!=2024.12.1
  - esmf >=8.8.0=nompi_*
  - lxml
  - mache >=0.15.0
  - matplotlib-base >=3.8.2
  - netcdf4
  - output_viewer >=1.3.0
  - numpy >=2.0.0,<3.0.0
  - pywavelets
  - scipy
  - xcdat >=0.10.0,<1.0.0
  - xesmf >=0.8.7
  - xskillscore >=0.0.20
  # Testing
  # =======================
  - pytest
  - pytest-cov
  # Documentation
  # =======================
  - sphinx
  - sphinx_rtd_theme
  - sphinx-multiversion
  - sphinx-copybutton
  # Quality Assurance Tools
  # =======================
  # Run `pre-commit autoupdate` to get the latest pinned versions of 'rev' in
  # `.pre-commit.config.yaml`, then update the pinned versions here.
  - pre-commit >=4.2.0
  - types-PyYAML >=6.0.0
  - ruff=0.12.2
  - mypy=1.16.1
  # Developer Tools
  # =======================
  - tbump=6.9.0
  - ipykernel
